version: "2.2"
services: 

    elasticsearch: 
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.2
        ports:
            - 9200:9200
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1

    kibana:
        image: docker.elastic.co/kibana/kibana-oss:6.3.2
        ports:
            - 5601:5601
